# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0002_auto_20170703_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_folded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='play_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
