# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0003_auto_20170703_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='best_hand_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
