# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0004_table_best_hand_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='cardtel.Game'),
            preserve_default=False,
        ),
    ]
