# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0005_auto_20170703_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winning_score',
            field=models.IntegerField(default=7),
        ),
    ]
