# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0006_game_winning_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(max_length=1),
        ),
    ]
