# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardtel', '0006_game_winning_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_moves', to='cardtel.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game', through='cardtel.Player', to='cardtel.User'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cardtel.User'),
        ),
        migrations.AlterField(
            model_name='table',
            name='best_hand_score',
            field=models.IntegerField(null=True),
        ),
    ]
